spring:
  r2dbc:
    url: r2dbc:${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    properties:
      schema: kss
  flyway:
    url: jdbc:${DB_URL}
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    default-schema: kss